server:
  port: 8080

spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 123456

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springboot.entity

#  #开启驼峰命名
#  configuration:
#    map-underscore-to-camel-case: true

#showSql
logging:
  level:
    com:
      example:
        springboot:
          mapper: debug